### ISSUE TITLE
[FIXED] Install lineage on Ubuntu Phone fails.

### ISSUE THREAD

**Issue by HaleyACS** [Pablito2020/android_device_bq_krillin#1]
Hi mate,

was really surprised when seeing that you are working on that ROM.
Tried installing it on my Ubuntu Editions Aquaris 4.5, however when Booting, I just get "Jelly screen" with a sideline, and then it reboots (Looping).

From what I know, the Aquaris E4.5 and 4.5 Ubuntu Edition use the same hardware, reason I tried it.

Anything I can do to debug this?

**Comment by Pablito2020** [comment]
You must be on  the stock kitkat rom for install  it and boot it succesfully

**Comment by HaleyACS** [comment]
Well, I had the Stock Android on it before (Just confitgured for a user).

Just Re-Imaged it from scratch (I only have Android 5.0 available) and deleted all the rest.
After that - fastboot flash TWRP + Wipe: Dalvik Cache, Data, Cache and system

Then copy onto /sdcard using adb push: 
 addonsu-arm-signed.zip
 open_gapps-arm-6.0-nano-20170520.zip
 lineage-13.0-20170513-UNOFFICIAL-krillin.zip

and install these with TWRP.
Will try it now again, after re-installing the Stock Android 5.0

Do you by chance have a link for the Android Kitkat 4.4? Thx
Updated: Got the latest version (My  spanish is a little rusty ;) ).
https://www.bq.com/es/support/aquaris-e4-5/support-sheet

Will implant 4.4 and try again.

Last question: Are the instructions here: http://www.cyanogenmods.org/forums/topic/lineage-os-13-aquaris-e4-5-krillin-marshmallow-rom/
the correct ones to follow?

Thanks

**Comment by HaleyACS** [comment]
One other thing - I am not able to install TWRP when on Stock ROM -> 4.4.x
twrp-3.1.1-0-krillin.img

~/Downloads/BQ_E45$ fastboot flash recovery twrp-3.1.1-0-krillin.img
sending 'recovery' (8412 KB)...
OKAY [  0.314s]
writing 'recovery'...
FAILED (remote: 
partition 'recovery' not support flash)
finished. total time: 0.320s

**Comment by Pablito2020** [comment]
Try it via mtk flashtools app

**Comment by HaleyACS** [comment]
So - thx for the hint.

Here is what I did, in order to get it to work (Maybe that should be updated in the previous Howto link):

1. Installed plain Kitkat 4.4.2
2. Installed TWRP through mtk flashtool (renamed twrp-krilling to recovery, and only loaded that one, untagged the others)
3. Rebooted - used "adb reboot recovery" to boot into recovery
4. In TWRP, Wiped: Davlik, Cache, system and data directory
5. Installed: lineage-13.0-20170513-UNOFFICIAL-krillin.zip
    open_gapps-arm-6.0-pico-20170520.zip and addonsu-arm-signed.zip (In that order)
6. Rebooted

and I see the Cyanogenmod animation at boot up :)  :+1: 
What is weird is that it does not work from the plain 5.0 Android that is provided by the Manufacturer too.

Do you plan to submit it to be officially supported by Lineage ? Would be nice! :}

**Comment by Pablito2020** [comment]
Proud to listen that you could finally install the rom! :)
And about the official builds.... In my opinion is imposible have official builds in this device because I'm using leaked source by MTK... And Lineage OS may have problems with that...
But, my unofficial builds have OTA integrated on it... So... Why we need official? 

Cheers,
Pablito2020

**Comment by plumpsack** [comment]
@HaleyACS ,
after you flashed your device from kk or cm13, with lineage-13.0-20170513-UNOFFICIAL-krillin.zip, you didn't loosed your IMEIs?

How did you made that?

**Comment by HaleyACS** [comment]
Can't tell, and I don't care as I don't have a "locked" contract (I never have). I always buy the phones I want to my conditions.
But, why would I loose my IMEI? isn't it bound to the phone itself? Like the Mac/Hw-Address of the network card?

anyway - just booted up my phone (it is a phone I play with -> ubuntu phone etc.), and you re right, I don't have a IMEI anymore (dual slot). All empty...
Hmmm. What to do now?

**Comment by Pablito2020** [comment]
Install the 21 may version. Imei is fixed on that version 😉

**Comment by plumpsack** [comment]
lineage-13.0-20170520-UNOFFICIAL-krillin.zip - same error, unknown baseband and no IMEIs

BUT,
lineage-13.0-20170521-UNOFFICIAL-krillin.zip is working fine!

Many thanks :)
