### ISSUE TITLE
mobile internet

### ISSUE THREAD

**Issue by martinbolte** [Pablito2020/android_device_bq_krillin#12]
Is there a chance for mobile internet to be fixed or to get it fixed? I wonder, because it has been working in previous versions. Besides that this rom is running brillantly on my phone. Thanks for all you work!

**Comment by MagnusAlm** [comment]
What version are you running?
Prebuild or have you compiled it yourself?

**Comment by martinbolte** [comment]
I used the prebuild rom lineage-14.1-20170912-UNOFFICIAL-krillin.zip from here:

https://androidfilehost.com/?fid=817550096634798915

**Comment by MagnusAlm** [comment]
I had the same problem with that one, for what I could see, I guess it didn't read the sim card correctly.
Have you tried setting the APN values manually?

I didn't put much time on it, but I think sms and calling worked for me, but not mms (but of course, you need working mobile data for that.).

**Comment by Nobby888** [comment]
I have the same problem with the mobile internet. Tried to set the APN manually, but still no luck. Any progress?
But all the rest ist running flawlessly, keep up the good work.

**Comment by Nobby888** [comment]
Has anyone managed to get the mobile internet, with the 14.1-build, working?

**Comment by martinbolte** [comment]
Only using the lineage 13 rom, which for me proved to be quite unstable and getting into boot loops. I finally switched back to the Lollipop stock rom, rooted it and uninstalled all Google apps, which works fine for me.

**Comment by karlkashofer** [comment]
Same for me, mobile internet is not working on 14.1-20170912

**Comment by MagnusAlm** [comment]
I've managed to get mobile internet working with device_bq_krillin cm-14.1 by adding mtk-ril.so and librilmtk.so from https://github.com/DeVviL/android_vendor_highscreen_giraffe/tree/lineage-14.1/proprietary/lib to vendor_bq_krillin cm-14.1.

**Comment by aleshorak** [comment]
Hi, that sounds great - do you please publish the ROM for testing? Can it be expected to work the same as lineage-14.1-20170912 by Pablito except for the mobile data libraries?

In the last week, I have tried four ROMs:
- lineage-14.1-20170912-UNOFFICIAL-krillin.zip by Pablito2020 - very good except the mobile internet not working

- lineage-13.0-20170521-UNOFFICIAL-krillin.zipby Pablito2020  - after installing more applications it has the boot loop problem

- lineage-13.0-20180103-UNOFFICIAL-krillin.zip by you - probably no boot loop problem, but ADB cannot authorize and addon-su application does not work (installation ok, su binary not working). btw - in lineage-13.0 by Pablito the su application is included directly in the main ROM.

- Firmware 2.1.0 - Android Lollipop by BQ - works, but Lollipop is already quite old and has its own problems (currently e.g. tedious Optimizing applications after every reboot)

so I am eagerly waiting for one of the lineage ROMs with the problems solved :-)

**Comment by MagnusAlm** [comment]
@aleshorak 

I haven't tested ADB on my cm-13.0 build yet but I've used for 2 weeks without any issues.

The problem with ADB and addon-su might be because it wasn't compiled with "su" enabled. I will test that.

**Comment by MagnusAlm** [comment]
Here is the link for 14.1

https://drive.google.com/drive/folders/1aL37MtQKP__w8XApOTe_mxsYkWdb0i6E?usp=sharing

It was built this morning, so I've just done some rudimentary testing.

What this build differs from Pablitos repositorys:

Kernel 14.1
Fixed the "off mode charging bug" by removing two patches from kernell 14.1:
https://github.com/Pablito2020/android_kernel_bq_krillin/issues/2
(actually it's the 14.1-f2fs with all the extra patches from 14.1 except those two ^^)

Vendor 14.1
Changed librilmtk.so and mtk-ril.so on vendor 14.1

Device 14.1
Copied most of the stuff from device 14.0. catalogue structure is the same as on 14.1 tho.
The ril is the same as 14.1.
(I've managed to build on 14.0, but it doesn't boot...) 

I'll try to fork Pablitos stuff and add my patches for viewing later. I'm a noob at this stuff and just learning by doing. ;-)

What I've tested:

sms
mms
mobile data
wifi
gps
adb (just logcat)

Not tested:

Camera (has worked before on my builds)
FM radio (has worked before on my builds)
Wifi on a hidden SSID (been too lazy to fiddle with my wifi-router.)

Not working:
Gestures ("double tap 2 wake" and "haptic feedback" settings)

**Comment by aleshorak** [comment]
Thanks a lot, going to give it a try (fifth one :-)). I suppose lineage-14.1-20180118-EXPERIMENTAL-krillin.zip is the right file, not the ota one?

**Comment by MagnusAlm** [comment]
For what I know they are exactly the same.

**Comment by aleshorak** [comment]
Installation went ok, but the result looks the same as with lineage-14.1-20170912-UNOFFICIAL - no mobile data :-(

the android Testing mode (*#*#4636#*#*) says: 
Voice service: Running
Data service: Disconnected
Voice network type: HSPA
Data network type: Unknown

I have checked APN setup, it is correct. Standard sms and voice work ok.

**Comment by MagnusAlm** [comment]
Well, my fix doesn't seem universal then.
I will do some more experiments next week. 

Almost done with a new build of cm-13.0 with su enabled.

Will do a quick test of it and post a link if it seems ok.

**Comment by MagnusAlm** [comment]
adb works now on 13.0

https://drive.google.com/open?id=1ACRa6WPqE8ZgH9_GFMRVtdFJFPmYPD80

**Comment by aleshorak** [comment]
super, I can confirm that 13.0 works great, mobile internet ok, adb+su works and no reboot loops (which were the [problems of previous 13.0 builds](../issues/13)

**Comment by martinbolte** [comment]
Dear Magnus,
thanks a million for your efforts. I have your ROM 14.1  installed on my E4.5 and it runs like a charm! 
Mobile data working out of the box.

**Comment by MagnusAlm** [comment]
@martinbolte  That is great. I've got around to make forks of Pablitos stuff and added my patches to it.
It differs a bit from the rom you uses since I've taken the 'ril' stuff from  https://github.com/DeVviL/android_device_highscreen_giraffe, fixed wifi hotspot and removed 'Gestures'.

I'm testing building it right now.
What I know that doesn't work is wifi on a network with a hidden SSID.
And it seems that my telephone number shows up as unknown when calling, might be related to my sim card, will test with another.

**Comment by MagnusAlm** [comment]
Uploaded the new build to the old link, created sub folders named after day of build.

If they aren't accessible let me know.

**Comment by karlkashofer** [comment]
Mobile data working on lineage-14.1-20180125-EXPERIMENTAL-krillin.zip !
Will test some more, thanks a lot !
Great !

**Comment by MagnusAlm** [comment]
@karlkashofer  ;-)

I've might found what is missing for the hidden SSID problem:

https://github.com/danielhk/android_device_lenovo_aio_otfp/blob/cm-14.1/platform_patches/wpa_supplicant_8.patch

I'll test that.

**Comment by karlkashofer** [comment]
Well, it turns out mobile internet worked just once. Cant get it working any more. Just wont switch on.

bugger.

**Comment by aleshorak** [comment]
@MagnusAlm 
great! for me mobile data works in 14.1-20180125 (which was not the case for any of the previous 14.1 ROMs). and it seems stable so far, not just once.

**Comment by karlkashofer** [comment]
Hmm, are you using two sim cards ?

I have two in mine, maybe thats confusing something. However, i removed
one of them and mobile data still would not work.

Its soo annoying...



Am 2018-01-27 um 13:27 schrieb aleshorak:

**Comment by aleshorak** [comment]
@karlkashofer 
I have only one SIM card. In 13.0 ROMs it was working ok, but no luck in any 14.1 ROM until this last one.

**Comment by MagnusAlm** [comment]
Hm, the data problem seems to be dependent on what operator you have. it seems like only GSM works, got a SIM that seems to requires WCDMA and no data on neither the 180118 nor the 180125 build.

Could be the radio baseband firmware that is the issue, cm 13.0 rom has: "MOLY.WR8.W1449.MD.WG.MP.V1,2015/02/11 17:50" (which seems to be stock lolli-pop version)
 
Whereas 14.1 has:
"WR8.W1412.MD.WG.GMP.SP.W14.26.P3,2014/08/15 11:39" 

Pablo changed this in https://github.com/Pablito2020/android_vendor_bq_krillin/commit/f09c808ae30c944c9817e5fb205c3e9afb665880 170922.

**Comment by MagnusAlm** [comment]
I've had some success, made a build with the modem firmware from vendor cm13.0.

Got mobile data working on the sim that wants WCDMA by using the app "hidden settings".

Under the menu "Radio Info" there is a switch, a bit down, for turning the power on/off for the mobile radio.
(I'm a bit uncertain about the translation from Swedish tho...)

So, by turning the mobile radio off and on, then waiting  for it to reconnect to service.
Then I turn mobile data off and on.
After a couple of seconds I get mobile data.

This isn't working on the 180125 build, so it must have to do with the change of modem firmware.
And something else must be changed also, but I'll be digging some more.....

**Comment by MagnusAlm** [comment]
First: I did some piss poor testing with the builds made 180118 and 180125.
I never tested all sim cards I have back then, I was just happy that the first one I tested worked.

What I've done now (after a weekend of trial and terror), is basically a reversing all changes related to telephony back to where it was around 170912, which is also the same binaries used for the 13.0 branch. 
What differs now from then is probably some bugs that has been fixed in the Lineage cm-14.1 source.

Mobile data now works on both the sim cards that I have and has that capability for mobile data.
The catch is that you have turn off and on the mobile radio modem after boot.

This can bee done two ways.

1. Either enter this code as if you where dialing: 
 `*#*#4636#*#*`

A menu will pop up called "Testing".
Press "Phone information" and a bit down on the screen you have "Mobile radio power", tap the button to the right of it, watch the mobile signal strength indicator in the status bar go blank, then tap the button again to turn it back on.
After a few seconds, if it works for you as it does for me, you should have a mobile data connection.

2. Or, install the app "Hidden android settings" from google play store.
Start that app and choose "RadioInfo", this will take you to the same menu as the example above.

This how far I've come this weekend, it will probably take some more time to figure this out.
The cause of it can be that Lineage OS 14.1 is not compatible backwards with the old Mediatek drivers/binaries/stuff or it might be a kernel bug, that one is in dear need of some TLC since it hasn't had any fixes applied since 171020, Pablo probably has been busy with studies/life or just lost interest. (and I don't blame him if he did.)

If you want to test it, you can find it here under 180203:
https://drive.google.com/open?id=1aL37MtQKP__w8XApOTe_mxsYkWdb0i6E

**Comment by karlkashofer** [comment]
Dear Magnus !

Thanks a lot for your work !
I flashed your 0203 build, but it seems it does not recognize my
sim-cards. Both slots are reported as empty, phone is not asking for the
pins.

any ideas ?
cheers,
KK

Am 2018-02-04 um 17:27 schrieb Magnus:

**Comment by MagnusAlm** [comment]
Tried turning the phone off and on?

I get that too sometimes on a "soft" reboot, a hard reboot helps.

**Comment by karlkashofer** [comment]
Ok, turning on and off actually brought back the sim cards. Then i did
the *#*# magic but still no data on any of my two sims.



Am 2018-02-04 um 19:20 schrieb Magnus:

**Comment by martinbolte** [comment]
Hello Magnus,

one feedback from my side. I am using 14.1-20180118-EXPERIMENTAL-krillin 
you posted in January. Mobile data did work seamlessly, but recently the 
service seems to get dumped short after booting the phone. To get it 
back I need to restart the phone.

Is there a way to reactivate the service lets say via command?



Am 31.01.2018 um 20:30 schrieb Magnus:

**Comment by MagnusAlm** [comment]
@martinbolte For restarting the telephone mode you can try this:

This can bee done two ways.

    Either enter this code as if you where dialing:
    *#*#4636#*#*

A menu will pop up called "Testing".
Press "Phone information" and a bit down on the screen you have "Mobile radio power", tap the button to the right of it, watch the mobile signal strength indicator in the status bar go blank, then tap the button again to turn it back on.
After a few seconds, if it works for you as it does for me, you should have a mobile data connection.

    Or, install the app "Hidden android settings" from google play store.
    Start that app and choose "RadioInfo", this will take you to the same menu as the example above.

You might need to do it twice on 18018 and 180125 builds.

**Comment by MagnusAlm** [comment]
@karlkashofer with the phone info tool, have you tride setting something else than the default "WCDMA preferred" under "networktype"?

I think they correlate like this:

2G    GSM or UMTS

3G    CDMA, WCDMA or TD-SCDMA

4G    LTE  (I'm pretty sure that this is not supported by the hardware tho.)

**Comment by martinbolte** [comment]
@MagnusAlm Dear Marcus, one more feedback. I could not get the broken mobile data issue fixed with the 14.1-20180118-EXPERIMENTAL-krillin- Rom, but today I tried the 14.1-20180203-EXPERIMENTAL-krillin build and it worked exactly as you described. Mobile data working. Thank you so much for supporting us!
Martin

I think with the two builds that MagnusAlm made for lineage 13 and 14, providing mobile data (see links above) this issue can be considered as closed

**Comment by martinbolte** [comment]
I think with the two builds that MagnusAlm made for lineage 13 and 14, providing mobile data (see links above) this issue can be considered as closed
