### ISSUE TITLE
IMEI deletion upon flash

### ISSUE THREAD

**Issue by EBjerrum** [Pablito2020/android_device_bq_krillin#17]
Hi 
  I tried to install Lineage OS 14.1 on my BQ 4.5 ubuntu edition, but somehow the IMEI numbers gets deleted. I'm a beginner at installing custom ROMs so I'm not sure where in the process I may do it wrong.

I flashed stock 4.4 kitkat via the SP_flashtool.
Installed TWRP as a custom recovery
booted into recovery and wiped system, cache, data and dalvik
installed lineage-14.1-20170912-UNOFFICIAL-krillin.zip and Open-Gapps-nano

When I reboot the IMEI numbers are empty and the SIM won't register.

From what I found on the net, the information should reside on some efs partition that I should have backed up, except there is no efs partition.

I found how I could reset them using MTK Engineering mode app in the stock ROM, but thats not in the Lineage OS ROM.

Any tips/ideas where I may do it wrong?

**Comment by MagnusAlm** [comment]
I suspect this a random behaviour on some BQ Aquaris E4.5 units, from your description it looks like you've done it correctly.

I had this problem with my second phone also, (also the Ubuntu edition), after a few flashes both IMEI would pop up.

But the Lineage rom you are testing doesn't work with all telephone operators.

**Comment by EBjerrum** [comment]
I don't have the model anymore
