### ISSUE TITLE
[FIXED] IMEI lost after installing lineage-13.0-20170521-UNOFFICIAL-krillin.zip

### ISSUE THREAD

**Issue by Mangnoppa** [Pablito2020/android_device_bq_krillin#2]
Hey Pablito,

first of all great work! Lineage 13 works nearly as expected. Unfortunately my IMEIs are gone after flashing. I didn't erase the NVRAM. After reflashing the stock ROM everything is working fine without doing anything.

The known apps for changing the IMEI like 'MTK Engineering Mode' are not working. It says my device has no Mediatek chip.

Do you have any idea what I can do?

Mangnoppa

**Comment by Pablito2020** [comment]
You must take a backup of your imei first! With an app like for example mobileuncle tools, and then, restore it...
It is a MUST in mtk devices with nvram partition.
Cheers

**Comment by Mangnoppa** [comment]
Thanks for the reply, I magically don't have this issue anymore, the IMEIs are back. 

But I have a "Emergency Calls only - no SIM" Error. Do you have any idea what's causing this? I tried almost anything from the first ten google result pages.

**Comment by Pablito2020** [comment]
Send me ss about device information/serial build number...
So I can see If you have a working modem installed on your device..

And maybe a logcat when you are trying to activate your mobile data or when you are trying to call will help.
Cheers
Pablito2020

**Comment by Mangnoppa** [comment]
Hey Pablito,

it seems you are right. Something is wrong with the modem. The first picture is from the stock rom (android 4.4) and the second is the lineage. I don't know how to fix this. Do you have any idea?

I also attached the last ~500 lines of the logcat. I couldn't activate anything SIM-related but i tried to call.

Thanks for your help. I would really like to use and contribute to your work.

![stock4 4-2](https://cloud.githubusercontent.com/assets/11314222/26762464/2d28b66a-4943-11e7-9aa0-2a1613c5b8c8.png)

![lineage-2](https://cloud.githubusercontent.com/assets/11314222/26762529/135fa864-4944-11e7-917f-f29ba242bcce.png)


[logcat-short.txt](https://github.com/Pablito2020/android_device_bq_krillin/files/1050397/logcat-short.txt)

**Comment by Pablito2020** [comment]
It seems that you only have 1 imei available...
Try to change the simcard1 to simcard2 or viceversa.


_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by plumpsack** [comment]
"You must take a backup of your imei first! ..." He/She don't need that!
Flash with mtk-tools 
https://s3.amazonaws.com/phonefirmwares/Aquaris+E+4.5/1.0.0_20140616-1411_krillin_bq-FW.zip
Use 
https://dl.twrp.me/krillin/twrp-3.1.1-0-krillin.img
for recovery!

Boot into recovery.

Install latest CM.zip (LineageOS) and latest root-tool (zip) for ->LineageOS<- via TWRP !!!
:)
