### ISSUE TITLE
[FIXED] addonsu root

### ISSUE THREAD

**Issue by RenEgaDe-S2** [Pablito2020/android_device_bq_krillin#3]
Flashes fine, root options enabled but no root?

**Comment by Pablito2020** [comment]
You have to download the supersu.zip attached in the lineage os post for this device in htcmania.com

Cheers.
Pablito2020

_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
