### ISSUE TITLE
Hidden ssid and 14.1

### ISSUE THREAD

**Issue by plumpsack** [Pablito2020/android_device_bq_krillin#5]
lineage-14.1-20170912-UNOFFICIAL-krillin

First, thanks for making the new version public.

But it has got the same error as here

https://forum.xda-developers.com/k3-note/orig-development/rom-custom-nougat-roms-k-3-note-t3513466

hidden ssid is not working and blocking scans.

Could you please fix that?

Thanks :)

**Comment by Pablito2020** [comment]
WIll try... 
Can you try to provide logcats?
Thanks for reporting the bug

**Comment by Pablito2020** [comment]
Okay, bug fixed porting the mt6752 wifi hal for Nougat to mt6582
Commit here: https://github.com/Pablito2020/android_device_bq_krillin/commit/a0b5f75e21384975125f05198a73a4a1e85a7eb2

I will close the issue
